//
// Created by DANIEL on 30/12/2025.
//

#ifndef T_CNICAS_DE_COMPUTACI_N_CIENT_FICA_CONFIG_H
#define T_CNICAS_DE_COMPUTACI_N_CIENT_FICA_CONFIG_H

typedef double real_t;

#endif //T_CNICAS_DE_COMPUTACI_N_CIENT_FICA_CONFIG_H